name: Deploy Static Website to GitHub Pages

on:
  push:
    branches:
      - main

permissions:
  contents: read
  pages: write
  id-token: write

jobs:
  deploy:
    environment:
      name: production   # 👈 This links it to your "production" environment
    runs-on: ubuntu-latest

    steps:
      - name: Checkout source
        uses: actions/checkout@v4

      - name: Setup Pages
        uses: actions/configure-pages@v4

      - name: Upload static files
        uses: actions/upload-pages-artifact@v3
        with:
          path: .   # 👈 This tells GitHub to deploy index.html, styles.css, etc.

      - name: Deploy to GitHub Pages
        id: deployment
        uses: actions/deploy-pages@v4
